source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3' 
gem 'haml'
gem 'devise'

gem 'friendly_id' 
gem 'verbs' 
gem 'paperclip' 
gem 'chronic' 
gem 'twitter' 
gem 'delayed_job' 
gem 'delayed_paperclip' 
gem 'warden' 
gem 'will_paginate' 
gem 'formtastic' 
gem 'rspec', '>= 1.2.0' 
gem 'rspec-rails', '>= 1.2.0'
gem 'shoulda' 
gem 'mocha' 
gem 'factory_girl' 
gem 'compass', '>= 0.10.1'
gem 'mocha' 
gem 'timecop' 
gem 'twitter' 
gem 'twitter-login', '~> 0.2.1', :require=>"twitter/login"
