development:
  access_key_id: 02D8HGYD1WMDGJZNKER2
  secret_access_key: VjgFt/L8c8o7QqNGBPq80iynmEYHAUVpM8viNI0N
  bucket: dev_kuwest_profiles
test:
  access_key_id: 02D8HGYD1WMDGJZNKER2
  secret_access_key: VjgFt/L8c8o7QqNGBPq80iynmEYHAUVpM8viNI0N
  bucket: test_kuwest_profile
production:
  access_key_id: 02D8HGYD1WMDGJZNKER2
  secret_access_key: VjgFt/L8c8o7QqNGBPq80iynmEYHAUVpM8viNI0N
  bucket: kuwest_profiles